id: I754B9D44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:05:57+00:00'
last_modified: '2022-06-07T17:58:11.863583+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30410
  title: ངེས་དོན་དགའ་ཚལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    9E1B:
      image_group_id: I1KG26253
      title: ''
      total_pages: 0
      order: 1
      base_file: 9E1B.txt
    A365:
      image_group_id: I1KG26254
      title: ''
      total_pages: 133
      order: 2
      base_file: A365.txt
    4D0B:
      image_group_id: I1KG26255
      title: ''
      total_pages: 0
      order: 3
      base_file: 4D0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
